# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20170815_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='good/thumbnails'),
        ),
    ]
