# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 19:23
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('page', '0004_auto_20170820_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='\u0422\u0435\u0433\u0438'),
        ),
    ]
